version : '3'

services :

  mongodb:
    build : "./dockerfiles/mongo"
    image: mongo-rj
    ports :
    - "27017:27017"
    volumes:
    - /data/db:/data/db
    container_name : mongo-rj
    networks :
      netrj :
        ipv4_address: 172.18.0.2

  backend :
    build : "./dockerfiles/backend"
    image : backend-rj
    ports :
    - "5000:3000"
    container_name : backend-rj
    volumes:
    - ./backend:/src/rj

    networks :
      netrj :
        ipv4_address: 172.18.0.3

  frontend :
    build : "./dockerfiles/frontend"
    image : frontend-rj
    ports :
    - "4200:4200"
    - "49153:49153"
    container_name : frontend-rj
    volumes:
    - ./frontend:/src/rj

    networks :
      netrj :
        ipv4_address: 172.18.0.4

networks:
  netrj:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
